import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  ImGoogle,
  ImFacebook,
  ImTwitter,
  ImArrowDownRight2,
} from "react-icons/im";
import { useState, useRef } from "react";
// const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const [width, setWidth] = useState("40");
  const [height, setHeight] = useState("20");
  const [text, setText] = useState("Create a New Account");
  const [opacity, setOpacity] = useState("1");
  const [position, setPosition] = useState("-40px");
  const [registeration, setRegisteration] = useState(true);
  const [signUser, setSignUser] = useState(false);
  const linkRef = useRef();
  const navigate = useRouter();

  const handleGrow = () => {
    setWidth("200");
    setHeight("200");
    setOpacity(".9");
    setPosition("30rem");

    setTimeout(() => {
      setWidth("40");
      setHeight("20");
      setOpacity("1");
      setPosition("-40px");
      setText("Sign in user");
      setRegisteration(false);
      setSignUser(true);
      if (text === "Sign in user") {
        setText("Create a New Account");
        setRegisteration(true);
        setSignUser(false);
      }
    }, 1000);
  };

  const regDivistion = (
    <div className={styles.inputContainers}>
      <input className={styles.inputs} placeholder="First name" required />
      <input className={styles.inputs} placeholder="Last name" required />
      <input
        className={styles.inputs}
        placeholder="Email"
        required
        type="email"
      />
      <input
        className={styles.inputs}
        placeholder="Password"
        required
        type="password"
      />
    </div>
  );

  const signDivistion = (
    <div className={styles.inputContainers}>
      <input
        className={styles.inputs}
        placeholder="Email"
        required
        type="email"
      />
      <input
        className={styles.inputs}
        placeholder="Password"
        required
        type="password"
      />
    </div>
  );
  const handleReg = (e) => {
    e.preventDefault();
    navigate.push("/Dashboard");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form className={styles.form}>
          <div
            className={styles.formCircular}
            style={{ width: `${width}rem`, height: `${height}rem` }}
            onClick={handleGrow}
          >
            <span style={{ color: "#fff", cursor: "pointer" }}>
              <ImArrowDownRight2 size="2rem" /> Click me
            </span>
            <h1
              className={styles.formHeading}
              style={{ opacity: `${opacity}` }}
            >
              {text}
            </h1>
          </div>
          <h1 className={styles.centerText} style={{ left: `${position}` }}>
            Calcul-x
          </h1>
          {registeration && regDivistion}
          {signUser && signDivistion}
          <div className={styles.buttonDivContainer}>
            <button className={styles.regButton} onClick={handleReg}>
              register
            </button>
            <Link href="/Dashboard" className={styles.link} ref={linkRef}>
              d
            </Link>
          </div>
          ;
        </form>
      </main>
    </>
  );
}
